dist: focal

language: node_js
node_js:
  - 10

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - build-essential

cache:
  yarn: true
  directories:
    - $HOME/.cache/yarn
    - ./node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: Tests
      name: BUILD
      script: yarn build --progress=false
    - name: UNIT TEST
      script: yarn test:ci
    - name: LINT
      script: yarn lint:ci
    - name: CYPRESS
      script: |
        yarn cypress install
        yarn run config
        tools/cypress-start-and-test.sh
