# Global settings applied to the whole site.
#
# more informations on : https://www.netlify.com/docs/netlify-toml-reference/

[build]
  base    = "./"
  publish = "./dist/acrabadabra/"
  command = "yarn build"

[context.production]
  command = "yarn build:prod"

[context.deploy-preview]
  command = "yarn build:dev"

[context.branch-deploy]
  command = "yarn build:dev"

[context.staging]
  command = "yarn build:staging"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
