# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-dependencies-{{ checksum "yarn.lock" }}

      - run: sudo apt-get install build-essential
      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn run config
      - run: yarn build --progress=false
  test:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: sudo apt-get install libxss1
      - run: yarn test
  cypress:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: cypress
      - run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - run: yarn cypress install
      - save_cache:
          key: cypress
          paths:
          - ../.cache/cypress
      - run: yarn run config
      - run: tools/cypress-start-and-test.sh
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos
  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn lint:ci

workflows:
  test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - cypress:
          requires:
            - install
      - lint:
          requires:
            - install
