name: Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - "master"
      - "staging"

jobs:
  tests:
    name: Test & Preview

    # Avoid duplicate deploys when the head branch of the PR already trigger the job
    if: github.head_ref != 'staging' && github.head_ref != 'demo'

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn ci:test
        env:
          REACT_APP_NAMESPACE: ${{ github.event_name == 'push' && steps.branch-name.outputs.ref_branch || 'preview' }}
